name: CI

on:
  schedule:
    - cron: '5 0 * * 1'
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-luna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push remnrem/luna
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: remnrem/luna:latest

  build-lunalite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push remnrem/lunalite
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.lite
          push: ${{ github.event_name != 'pull_request' }}
          tags: remnrem/lunalite:latest

  build-lunapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push remnrem/lunapi
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.lunapi
          push: ${{ github.event_name != 'pull_request' }}
          tags: remnrem/lunapi:latest
